### ISSUE TITLE
Failure finding gurobi when directly setting number of clusters

### ISSUE THREAD

**Issue by Heronimonimo** [PyPSA/pypsa-eur#12]
When using the number of clusters in a command line call
`snakemake -R results/summaries/elec_s6_all_lc1.0_Co2L-3H_all`

It results in an error when using `cbc`:
```
INFO:pypsa.io:Imported network elec_s.nc has buses, carriers, generators, lines, loads, storage_units
INFO:pypsa.io:Imported network elec.nc has buses, carriers, generators, lines, loads, storage_units, transformers
INFO:__main__:Mapping all network lines onto a single 380kV layer
INFO:__main__:Simplifying connected link components
INFO:__main__:Removing stubs
WARNING:__main__:The configured solver `cbc` does not support quadratic objectives. Falling back to `ipopt`.
INFO:__main__:Clustering to 6 buses
WARNING: Could not locate the 'gurobi' executable, which is required for
    solver gurobi
WARNING:pyomo.solvers:Could not locate the 'gurobi' executable, which is required for solver gurobi
Traceback (most recent call last):
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmpiavuo4h_.simplify_network.py", line 299, in <module>
    n, cluster_map = cluster(n, int(snakemake.wildcards.simpl))
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmpiavuo4h_.simplify_network.py", line 261, in cluster
    clustering = clustering_for_n_clusters(n, n_clusters, potential_mode=potential_mode)
  File "/home/pypsa/pypsa-eur/scripts/cluster_network.py", line 154, in clustering_for_n_clusters
    n, busmap_for_n_clusters(n, n_clusters, algorithm),
  File "/home/pypsa/pypsa-eur/scripts/cluster_network.py", line 109, in busmap_for_n_clusters
    n_clusters = distribute_clusters(n, n_clusters, solver_name=solver_name)
  File "/home/pypsa/pypsa-eur/scripts/cluster_network.py", line 91, in distribute_clusters
    results = opt.solve(m)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pyomo/opt/base/solvers.py", line 541, in solve
    self.available(exception_flag=True)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pyomo/solvers/plugins/solvers/GUROBI.py", line 156, in available
    val = ILMLicensedSystemCallSolver.available(self, exception_flag)
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pyomo/opt/solver/ilmcmd.py", line 36, in available
    if not pyomo.opt.solver.shellcmd.SystemCallSolver.available(self, exception_flag):
  File "/home/.conda/envs/pypsa-eur/lib/python3.6/site-packages/pyomo/opt/solver/shellcmd.py", line 122, in available
    raise ApplicationError(msg % self.name)
pyutilib.common._exceptions.ApplicationError: No executable found for solver 'gurobi'
```

**Comment by euronion** [comment]
I think the issue is probably with [line 104 in cluster_networks.py](https://github.com/PyPSA/pypsa-eur/blob/2e02c8366e184f08711beb669a2bb9da3e1adb83/scripts/cluster_network.py#L104),
as the `globals()` is not shared into module functions.

As `'snakemake' in globals()` evaluates to `False`, the default `solver_name = gurobi` kicks in.
An (ugly) solution would be to use a dedicated argument for the function or to share it via `__builtins__`, but I guess @coroa has better ideas.

As a workaround you could locally edit [Line 107](https://github.com/PyPSA/pypsa-eur/blob/2e02c8366e184f08711beb669a2bb9da3e1adb83/scripts/cluster_network.py#L107) from `gurobi` to `cbc` .

**Comment by Heronimonimo** [comment]
Ah, did not look at that. Good find!

I have made a pull request #16 to change the fallback to `cbc` because that solver can be installed freely via conda-forge and is included in the `environment.yaml` after #11 is merged. Gurobi will then still be used when specified in the `config.yaml`.

**Comment by euronion** [comment]
Could you try #17 ? I can't test it at the moment, but it should fix the problem.
(Promoted the solver selection to be a function argument)

**Comment by coroa** [comment]
Wow, there's a lot to explain.

> When using the number of clusters in a command line call
> `snakemake -R results/summaries/elec_s6_all_lc1.0_Co2L-3H_all`

1. You involuntarily triggered an very specific feature: 
The network clustered to 6 buses as you know it is `elec_s_6.nc`.

You tried to look at `elec_s6_<scenario clusterings>_lc1.0_Co2L-3H_<configured countries>`, so if your `config.yaml : scenario : clusters` had `[ 8 ]`, snakemake wanted to generate the network `networks/elec_s6_8.nc`, which is derived from `elec_s6.nc`.

`elec_s6.nc` is a network in which the `simplify_network` rule does already cluster the network to 6 buses. It does this by importing functions from the `cluster_network` module. These functions live in a different namespace and are thus unable to see the `snakemake` object, which triggers your error.

`elec_s100_50.nc` for example is a network in which `simplify_network` clusters the network to 100 buses and in a second step `cluster_network` reduces it down to `50` buses. 

I suppose you rightly think WTF now :).

Well, let me provide a use-case where this makes sense:

In preliminary tests, it turns out, that the principal effect of changing spatial resolution is actually only partially due to the transmission network. It is more important to differentiate between wind generators with higher capacity factors from those with lower capacity factors, ie to have a higher spatial resolution in the renewable generation than in the number of buses.

This two-step clustering can take advantage of that fact (and allows to study it)
by looking at networks like `networks/elec_s100_50m.nc`. For this example `simplify_network` clusters to 100 buses and then `cluster_network` clusters to 50m buses, which means 50 buses for the network topology but only moving instead of aggregating the generators to the clustered buses. So in this network you still have up to 100 different wind generators, 2 at each bus on average.
 
2. You are mis-using the -R flag for snakemake. Please read up on it! If you don't understand it ask again.
