### ISSUE TITLE
Progressively increase co2_sequestration_potential for myopic optimization

### ISSUE THREAD

**Issue by lindnemi** [PyPSA/pypsa-eur#1212]
In myopic optimization the full co2 sequestration potential is available right away which can lead to unintended effect. E.g., in pypsa-ariadne we were seeing process emissions being fully sequestered already in 2030. 

A time dynamic limit would make more sense (e.g., 50 in 2020, 100 in 2030, 200 in 2045 -  suggestion by Tom).

See https://github.com/PyPSA/pypsa-ariadne/pull/168 for a DE specific solution

**Comment by nworbmot** [comment]
I suggest to make the config `sector: co2_sequestration_potential` from a static config into an investment-year-dependent config for myopic/perfect foresight. The parameter is only used in `solve_network.py` in the function `add_co2_sequestration_limit` and since I cannot foresee all the interactions with perfect foresight, maybe it's better if @lisazeyen implements it?
