### ISSUE TITLE
Work out why p_max_pu are different in myopic code for existing assets

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/pypsa-eur#1216]
There is some weirdness in the myopic foresight code either in `add_existing_baseyear` or `add_brownfield` whereby wind turbines built in the first investment year and before have different `p_max_pu` than later wind turbines, even though the wind turbine model stays the same. Here is an example for investment year 2025, where the first investment year is 2020.

![Screenshot from 2024-08-14 13-57-41](https://github.com/user-attachments/assets/ea1e0ca3-da50-40e8-a173-e6ff1ffd2aad)

**Comment by lisazeyen** [comment]
The difference appears due to the clustering of the renewable profiles in `add_brownfield.py` in the function [`def adjust_renewable_profiles`](https://github.com/PyPSA/pypsa-eur/blob/e273f4ec9d995a081d4973d9ddc448952d36e459/scripts/add_brownfield.py#L167-L216)

This was introduced with the year dependent turbine types. The capacity factors for different turbine types are not added directly to the electricity networks, since this would require having an electricity network for each investment period. Instead, they are overwritten in `add_brownfield` depending on the planning horizon. But the clustering of the renewable profiles 
```
# spatial clustering
  weight = ds["weight"].sel(year=closest_year).to_pandas()
  weight = weight.groupby(clustermaps).transform(normed_or_uniform)
  p_max_pu = (p_max_pu * weight).T.groupby(clustermaps).sum().T
  p_max_pu.columns = p_max_pu.columns + f" {carrier}"
```
is probably different than in PyPSA which seems to be [`capacity weighted average`](https://github.com/PyPSA/PyPSA/blob/083ad7000d53b28cf32e02cfabc8ec01002a757e/pypsa/clustering/spatial.py#L41)

In the long-term, when PR #1201 is merged this issue is going to be solved. In the meantime, the clustering of the `p_max_pu`should be adjusted to the clustering strategy in `cluster_network`
