### ISSUE TITLE
Negative electrical demand with coarse time resolution

### ISSUE THREAD

**Issue by cerealice** [PyPSA/pypsa-eur#1278]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

When I use a very aggregated time resolution (876H) my electricity demand becomes negative because in prepare_sector_network in add_industry the factor to remove the industrial electricity demand does not take into account the fact that the load is not on an hourly basis.
I solved this by creating inside add_industry a timesteo variable timestep = n.snapshot_weightings.iloc[0,0] and then using it to weight better the loads_t.p

<img width="495" alt="image" src="https://github.com/user-attachments/assets/37ca0967-4c39-4e6d-bd68-747efbff9ca2">

**Comment by koen-vg** [comment]
Could this simply be caused by setting `resolution_elec` to some non-false value but running a sector-coupled network? Currently, `prepare_sector_network.py` basically expects `resolution_elec` to be `False`, i.e. the network is not "supposed" to be time-aggreggated, and for sector-coupled networks this is only supposed to happen through `resolution_sector`. See also the discussion in https://github.com/PyPSA/pypsa-eur/issues/1277. I will note that this is warned against in the documentation (https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering), but that's of course easy to miss, and as I've written in the linked issue I don't think there should be any reason to allow two separate configuration option for elec-only and sector-coupled time resolution; by joining them we could avoid the kind of issues like the present one.

Hopefully the problem with negative demand goes away when you set `resolution_elec: false`.

**Comment by cerealice** [comment]
I confirm that the problem is solved when running a sector coupled network but with `resolution_elec: false`. It is indeed specified in the documentation
Still it would be interesting to continue on https://github.com/PyPSA/pypsa-eur/issues/1277.
Thanks for your help!
