### ISSUE TITLE
Update GLAES to current version

### ISSUE THREAD

**Issue by euronion** [PyPSA/pypsa-eur#156]
## Describe the feature you'd like to see

Update the `glaes` dependency to the current version and drop the fixed dependency on the `pypsa/glaes` fork. The single hotfix done in `pypsa/glaes` seems to have been implemented upstream in this [commit](https://github.com/FZJ-IEK3-VSA/glaes/commit/9454584b983ffa09eaa18c0fca25eb3ad1579bf6) .

## Current hinderance:
`ec.ExcludeRasterType(...)` seems to support only ranges for raster types in the new version.
But we're using a list of values to be included via `invert=True` here https://github.com/PyPSA/pypsa-eur/blob/bb3477cd693d1c8e77e75e61a1a7e1a4647e6a3c/scripts/build_renewable_profiles.py#L219

It does not seem as if this was ever officially supported.

I can't find a quick solution at the moment to invert the selection, i.e.
1. retrieve a set of `grid_codes` from corine 
2. do the inversion outside of `glaes`
3. Exclude the inverted set of `grid_codes`

**Comment by euronion** [comment]
Addition:

Ok, so `geokit` seems to be the major hinderance. @fneum and @coroa were already on this, see this PR: https://github.com/FZJ-IEK3-VSA/geokit/pull/1 

Any chance of updating / finishing it? :)

**Comment by fneum** [comment]
@euronion yes, I can look into this next week. I'd really like to drop the hotfix forks of `geokit` and `glaes`.

**Comment by fneum** [comment]
Related (for reference): https://github.com/PyPSA/pypsa-eur/pull/81

**Comment by dsryberg** [comment]
Hi guys, I hope you don't mind me popping in here. I just saw @euronion 's comment on my version of GLAES, and I tried to track down the issue which led me to this discussion.

First off, I am certainly the one to blame for the changes you required not being integrated previously. There are a few reasons which led to this which I could explain if you are interested but, in short, it was unintentional and I am trying to change these things now!

Secondly, and more importantly, I would be very happy to have your changes incorporated into the base GLAES repo, and if I can help with that please let me know how. I have made quite a few additions to GLAES since you originally forked the repository, however, so it might actually be easier to re-implement the needed change. Which, from what I understand, is just the ability to exclude a list of values from a raster dataset, yes? This is something I could do for you but, since the idea originated from your group, then I would prefer one of you receives the "credit" via a pull request. But in any case, I'd just like to let you know that I am available through github/email/telco to discuss the topic more.

**Comment by euronion** [comment]
> @euronion yes, I can look into this next week. I'd really like to drop the hotfix forks of `geokit` and `glaes`.

Great, let me know if I can be of assistance.

@dsryberg Thanks for the prompt reply and offer! 👍

**Comment by sevberg** [comment]
Hello again.

I just wanted to mention here as well that, following [this discussion on the GLAES repo](https://github.com/FZJ-IEK3-VSA/glaes/issues/2) with @euronion, I've pushed new versions 
 of GLAES (v1.1.8) and GeoKit (v1.2.8) which should hopefully solve your problem
