### ISSUE TITLE
one-node-per-country clustering becomes infeasible

### ISSUE THREAD

**Issue by anyexingluzk** [PyPSA/pypsa-eur#24]
I have tried with 37 nodes clustering, which works totally fine. However, if I want one-node-per-country, the cluster_network rule becomes infeasible with the following message:
```
  File "/home/zhu/pypsa-eur/.snakemake/scripts/tmpli1lgrnk.cluster_network.py", line 116, in busmap_for_n_clusters
    n_clusters = distribute_clusters(n, n_clusters, solver_name=solver_name)
  File "/home/zhu/pypsa-eur/.snakemake/scripts/tmpli1lgrnk.cluster_network.py", line 99, in distribute_clusters
    assert results['Solver'][0]['Status'].key == 'ok', "Solver returned non-optimally: {}".format(results)
AssertionError: Solver returned non-optimally
```
Also, I am not quite sure what is the reason to cluster the network twice. Please shed some lights on this.

**Comment by fneum** [comment]
I discussed with @anyexingluzk that this is due to subnetworks in e.g. DK, GB, IT, and <forgot one country>. So in `cluster_network.py` in `distribute_clusters(...)` for @anyexingluzk's specific case (one node per country) we should not group by subnetwork.
`
L = (n.loads_t.p_set.mean()
         .groupby(n.loads.bus).sum()
         .groupby([n.buses.country]).sum()
         .pipe(normed))
N = n.buses.groupby(['country']).size()
`
Does it make sense to add an option in `config.yaml`to ignore subnetworks when clustering? Like
`cluster_keep_subnetworks: False`

**Comment by coroa** [comment]
Connecting non-synchronous zones with lines will make the power flow unphysical. I don't think that's a good idea, or at least there should be a big fat warning message, that it only makes sense in the setting of a transport model (ie. only dispatchable links (with carrier='AC') instead of lines).

Definitely, it would be good to add a more helpful error message when less clusters than there are (country, synchronouous zones) pairs are requested!

**Comment by coroa** [comment]
Actually, I did add an `assert` statement that should have triggered about two weeks ago.
https://github.com/PyPSA/pypsa-eur/blob/7f3f096ba6268948006122448d3833c460b628b9/scripts/cluster_network.py#L74

@anyexingluzk You were not using the latest version, or did you?

**Comment by anyexingluzk** [comment]
@coroa Yes, you are right. I was not using the up-to-date version, but now I am. Also what you said about non-synchronous zones makes sense totally. Thank you very much for answering my question. Still, I have a little doubt about clustering the network twice. Maybe the two steps have different purposes?

**Comment by coroa** [comment]
They do have different purposes, yes! Perhaps my explanation in a previous issue is of help: https://github.com/PyPSA/pypsa-eur/issues/12#issuecomment-465690384 .
