### ISSUE TITLE
Revisit validity of solar CF correction factor

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#285]
TODO: 

- [ ] disable correction factor for solar pv if SARAH is selected.

**Comment by martavp** [comment]
Let me try to write down what I know (and what I don’t).

Ground surface radiation from reanalysis is known to have a higher error (and typically a positive bias) than satellite data [1-5]. Fundamentally, this is because the coarse spatial resolution of reanalysis (30x30 km in ERA5, 40x40 km in CFSR ) is not good enough to capture the cloud dynamics which strongly impact the radiation on the ground. Satellite resolution (~7x7 km) is not ideal but much better.


Hence, adding a correction factor for reanalysis could be justified, although is not the optimal way of correcting the bias [6]. However, I don’t see a clear justification for adding a correction factor when using SARAH satellite data. 

**Hence, I suggest only applying the correction factor if ERA5 data is used, but not if SARAH is selected.**

This was the default option before. The following code belongs to script *prepare_network.py* in the [Synergies paper](https://zenodo.org/record/1146666#.YYo1PbqkGUk)

>if options['ninja_solar']:
>     solar = pd.read_csv('data/renewables/ninja_pv_europe_v1.1_sarah.csv',
>      index_col=0,parse_dates=True)[nodes]
>   else:
>        solar = p_max_pu['solar'][nodes] * options['solar_cf_correction']

I would favour reverting to that rule, unless a new validation of SARAH shows something different.

To further justify my proposal, see below the map of solar capacity factors obtained with the current configuration (SARAH+correction factor) and the comparison with the map from [PVGIS](https://re.jrc.ec.europa.eu/pvg_download/map_index.html).

[elec_s370_37m_lv1.0__3H-T-H-B-I-solar+p3-dist1-cb27ex0_2020_solar.pdf](https://github.com/PyPSA/pypsa-eur/files/7503390/elec_s370_37m_lv1.0__3H-T-H-B-I-solar%2Bp3-dist1-cb27ex0_2020_solar.pdf)



![PVGIS_EU_2012_presentation](https://user-images.githubusercontent.com/30744159/140894742-a4c5518b-38d7-49f3-bc03-2ae6d69a442a.png)


Validating solar time series is difficult because:

- Reported solar electricity generation from TSO is probably also modelled (not all the solar installations are actually measured by the TSO).

- Installed capacities show large variabilities from year to year [7], which make historical capacity factors show high uncertainty.

- No good information on capacity layouts is available (many small solar installations are not registered). [8]

An additional problem with SARAH satellite data is that, if one tries to produce long-term time series to investigate interannual variability, some data gaps exist for years <1995 [9]


**References:**
 
[1] References of reanalysis (MERRA and MERRA-2) positive bias: Figure 6 and Figure 10 in http://dx.doi.org/10.1016/j.energy.2016.08.060 

[2] Reference of reanalysis (CFSR) positive bias: Figure 9 (right) in  https://doi.org/10.1002/pip.3126

[3] Reference on satellite date performing better than reanalysis

Figure 7 and 10 in http://dx.doi.org/10.1016/j.energy.2016.08.060

Figure 9 right https://doi.org/10.1002/pip.3126

[4] The main conclusion in https://doi.org/10.1016/j.rse.2017.07.013  is that Satellite data performs better than ERA-Interim reanalysis and ERA-Interim reanalysis shows a positive bias. (ERA-Interim has been superseded by ERA5).

[5] The European-wide correction factors in ninja are 0.948 for MERRA (because the model predicts higher output than historical data) and 1.094 for SARAH (because the model predicts lower output than historical data).  Table S1 in Suplementary of http://dx.doi.org/10.1016/j.energy.2016.08.060.

I cannot confirm the need for bias correcting SARAH. Discussion in section 6 of https://doi.org/10.1002/pip.3126

[6] The bias is not uniform but strongly depend on the cloudy/clear-sky conditions, Figure 3 in https://doi.org/10.1002/pip.3126

[7] See Figure Supplementary Figure 4 in Supplementary Materials.
https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-020-20015-4/MediaObjects/41467_2020_20015_MOESM1_ESM.pdf

[8] This new database could solve this issue. I haven’t checked it. 
https://www.nature.com/articles/s41586-021-03957-7

[9] Figure 10 in http://dx.doi.org/10.1016/j.energy.2016.08.060

**Comment by FabianHofmann** [comment]
@martavp thanks for that comprehensive clarification. Let's summarize all TODO's at the top.

**Comment by martavp** [comment]
Perfect, I just edited the TODO

**Comment by FabianHofmann** [comment]
> Perfect, I just edited the TODO

thanks, excuse me, I think I mixed something up there

**Comment by martavp** [comment]
No worries :)
