### ISSUE TITLE
Add floating wind turbines for sea deeper than 50 metres

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/pypsa-eur#36]
Need to research costs and grid connection options.
See existing Hywind park off Scotland, similar parks in Portugal, Japan, US, etc.

**Comment by ben0911** [comment]
I am currently working on a floating offshore wind project and investigating the grid connection options and the integration with energy vectors. Happy to help on this issue.

**Comment by fneum** [comment]
Hey @ben0911, cool, might be worth getting in contact with @p-glaum (p.glaum (at) tu-berlin.de) who will work on this on our end.

**Comment by Edudiro** [comment]
Very interested to adding floating offshore technology. What is the state of #284 ? Happy to help move it forward :)

**Comment by p-glaum** [comment]
Hi @Edudiro,

actually, it is already implemented in my PyPSA-Eur fork. To merge it with the PyPSA-Eur master, I just need some time and find cost assumptions for the different investment year, which I have not found yet. Unfortunately, the Danish Energy Agency only has fixed bottom offshore wind cost assumptions. If you know a reliable sources for floating offshore wind cost with different investment years, feel free to post them here.

**Comment by Edudiro** [comment]
Glad to hear @p-glaum,

It is trully difficult to find sources, given the early commercial stages of floating technology.
I usually follow NREL analysis , they have some nice models for offshore.

https://www.nrel.gov/docs/fy23osti/81819.pdf
This one presents a regression model (FORCE) which derives the learning rates of floating and fixed, and then projects their bottom-up-computed baseline costs to the future 

https://www.nrel.gov/docs/fy21osti/77384.pdf
This one is a rather site-specific analysis using a different model (ORCA), which is a deterministic LCOE model. The article only covers up to 2032, but provides a [data sheet](https://www.nrel.gov/docs/fy21osti/77384data.xlsx) with fitted data up to 2050.

If I find any new reliable source I will add it as well. 

Hopefully this can be implemented soon, maybe under a disclaimer regarding the lack of reliable data on this technology due to its early stages.
