### ISSUE TITLE
Validation of the Power System Model for 2019

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#363]
Strongly related to changes in #353 

**Note:** We should disable the simplify wildcard in order to keep most of the generators separately and therefore their costs and efficiencies.

# Validation methods 

We separate the validation into two steps:

# Validation of the Network pre-optimization  

## Powerplants 

- [x] Capacity totals per country and carrier for conventionals - [remove remaining duplicates](https://github.com/FRESNA/powerplantmatching/issues/66)   (@FabianHofmann )
- [x] Renewable capacities from OPSD dataset - per country or all of Europe? (@chrstphtrs, @martacki) 
  - [x] scaling of existing capacities (exogeneously) 
- [ ] Revise efficiencies of single plants (heuristics based on commissioning year/country?) (@lisazeyen)
- [ ] Must-run conditions for CHPs still need to be quantified ( @chrstphtrs , @FabianHofmann, @Irieo  )

## Cross-border Capacities

- [x] Double-check cross-border transmission capacities ( @Irieo, @martacki ) 
  - [ ] How does the spatial resolution affect the simulation?

## Costs 

- [ ] Add 2020 costs 

# Validation of the Network post-optimization

- [ ] Energy mix per country  
- [ ] Import/Export balances
- [ ] OCGT dispatch
- [ ] electricity price time series (with one node per bidding zone, NTCs rather than fraction of thermal rating, linearised unit commitment, ramping, CO2 certificate price time series from historical data, heat-led CHP, demand elasticity for energy-intensive industry and updated varied efficiencies of gas plants)

**Comment by chrstphtrs** [comment]
Preliminary result on renewable capacities from OPSD:
- OPSD data only contains 8 countries: CH, CZ, DE, DK, FR, PL, SE, UK (https://data.open-power-system-data.org/renewable_power_plants/)
- There are 2 disjunct data sets:
  - group of 8 individual country .csv ("renewable_power_plants_CH.csv" etc.), with 22 data columns
  - one collated .csv ("renewable_power_plants_EU.csv"), with 16 data columns
- Both are almost identical, except for a couple hundred data entries
- My hypothesis is that some data entries from the individual country .csvs are dropped because when slimming down data columns to 16, they become identical
- If hypothesis holds, collating individual csv is our best data source, but we are still lacking data on 20+ countries (among them ES, PT, NL, IT ...)

Next steps (for tomorrow):
- briefly test the hypothesis above to confirm
- research IRENA/other country statistics to compare totals (for these 8 countries), and thus judge quality of this database
- research alternative data source for individual installations in remaining 20+ countries to supply data for PyPSA-Eur

**Comment by FabianHofmann** [comment]
https://www.sciencedirect.com/science/article/pii/S2352340922006540?via%3Dihub
