### ISSUE TITLE
Harmonize cluster strategies

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#375]
The component-specific cluster strategies are currently placed and defined at different places. For example, we find two explicit definitions for generator strategies in `simplify_network` and two in `cluster_network`. I would be suggest to have a default strategy dict defined in `cluster_network` in the heading, following the pattern

```python
GENERATOR_STRATEGIES = {"p_nom_max": "sum", ...}
STORAGE_STRATEGIES = {...}
```
which can be imported in `simplify_network`, used and optionally updated wherever needed.

**Comment by FabianHofmann** [comment]
@martacki would you like to take care of this? Preferably after merging #353

**Comment by martacki** [comment]
Hm spotted a potentially major bug on the go:

`np.min` yields different results than `'min'` (this relates to the implementation in PyPSA networkclustering.py)
the default value in pypsa-eur, `pd.Series.min`, yields a different result than `np.min` (default value in PyPSA). This is also due to the implementation in PyPSA, but it's strange that the default values are different.

However, `pd.Series.min` is also different than `'min'`, which I find confusing.

For example, clustering all nodes for `AL` to a single one results in:
**p_nom_max using `pd.Series.min`:**
AL1 0 offwind-ac    3.365876e+03
AL1 0 onwind        5.447241e+04
AL1 0 solar         2.073256e+04

**p_nom_max using `'min'`:**
AL1 0 offwind-ac    1664.113463
AL1 0 onwind        2473.089762
AL1 0 solar          623.827571

**p_nom_max using `np.min`:**
AL1 0 offwind-ac    2.913907e+03
AL1 0 onwind        2.121509e+04
AL1 0 solar         1.966018e+04

So - I'm confused.
**Suggestion**: support only `str` entries, i.e. `'min'`. If 'min', then use the "np.min" result (that is the default in PyPSA, but not in PyPSA-EUR. Here are a few results for a 1-node Germany
**`'min'`**
DE1 0 offwind-ac    1294.961369
DE1 0 offwind-dc    1285.487999
DE1 0 onwind         714.729722
DE1 0 solar          493.959162

I think less then 3 GW wind for all of Germany (and similarly small numbers for other countries) will be infeasible for 100% RE (but might drive orange up, if extendable in the model).

**`np.min`:**
DE1 0 offwind-ac    1.341876e+04
DE1 0 offwind-dc    4.434512e+04
DE1 0 onwind        2.415236e+05
DE1 0 solar         3.218559e+05

**`pd.Series.min`:**
DE1 0 offwind-ac    1294.961369
DE1 0 offwind-dc    1285.487999
DE1 0 onwind         714.729722
DE1 0 solar          493.959162
Name: p_nom_max, dtype: float64

CCGT, OCGT, biomass, coal, lignite, nuclear, oil, ror are always inf.
Thoughts? @FabianHofmann @euronion
