### ISSUE TITLE
How to use the rule simplify_network

### ISSUE THREAD

**Issue by JanFrederickUnnewehr** [PyPSA/pypsa-eur#38]
Hello,

what is the difference between the `rule simplify_network:` and `rule cluster_network:`?
I have checked the `rule simplify_network:` and it is using the `simplify_network.py` for mapping all lines to the 380 kV level. Afterwards a cluster function `def cluster(n, n_cluster)` is called.
-Why is this cluster function used?
-Why the user can set a number behind the `elec_sXXX` for simplification?

After the simplification `rule simplify_network:` the `rule cluster_network:` is started.
Why we have a cluster function inside of the simplification method?

Is it possible to run the model without the simplification method / rule?
I tryed to run the snakemake without the `s` for simplification. For example: 

`snakemake results/networks/elec_256_lv1.0_EP-24H.nc`

But the `s` after the `elec_` is a needed expression. 

Thanks in advance,
Best Freddy

**Comment by coroa** [comment]
Hi Freddie,

> what is the difference between the `rule simplify_network:` and `rule cluster_network:`?

The rule `simplify_network` does up to four things, which you already saw in the [`__main__` body of the code](https://github.com/PyPSA/pypsa-eur/blob/63a6cebab24ae55eba21e02e8ec8f857ba00a628/scripts/simplify_network.py#L283):

1. An equivalent transmission network in which all voltage levels are mapped to the 380kV level by function [`simplify_network`](https://github.com/PyPSA/pypsa-eur/blob/63a6cebab24ae55eba21e02e8ec8f857ba00a628/scripts/simplify_network.py#L29).

2. DC only sub-networks that are connected at only two buses to the AC network are reduced to a single representative link by the function [`simplify_links`](https://github.com/PyPSA/pypsa-eur/blob/63a6cebab24ae55eba21e02e8ec8f857ba00a628/scripts/simplify_network.py#L134). The components attached to buses in between are moved to the nearest endpoint (offshore wind generators receive a `capital_cost` penalty to keep track of their connection cost).

3. Stub lines and links, ie dead-ends, are sequentially removed from the network by [`remove_stubs`](https://github.com/PyPSA/pypsa-eur/blob/63a6cebab24ae55eba21e02e8ec8f857ba00a628/scripts/simplify_network.py#L229). Components are moved along.

4. If a number was provided after the `s` (as in `elec_s500_...`), the network is clustered to this number of clusters with the routines from the `cluster_network` rule by the function [`cluster`](https://github.com/PyPSA/pypsa-eur/blob/63a6cebab24ae55eba21e02e8ec8f857ba00a628/scripts/simplify_network.py#L240). This step is usually skipped.

The rule `cluster_network` instead clusters the network to a given number of buses.

> -Why is this cluster function used?
> -Why the user can set a number behind the `elec_sXXX` for simplification?

As you found out for yourself, `elec_s100_50.nc` for example is a network in which `simplify_network` clusters the network to 100 buses and in a second step `cluster_network` reduces it down to 50 buses. 

Well, let me provide a use-case where this makes sense:

In preliminary tests, it turns out, that the principal effect of changing spatial resolution is actually only partially due to the transmission network. It is more important to differentiate between wind generators with higher capacity factors from those with lower capacity factors, ie to have a higher spatial resolution in the renewable generation than in the number of buses.

This two-step clustering can take advantage of that fact (and allows to study it)
by looking at networks like `networks/elec_s100_50m.nc` (note the additional `m` in the `cluster` wildcard). For this example `simplify_network` clusters to 100 buses and then `cluster_network` clusters to `50m` buses, which means `50` buses for the network topology but only moving instead of aggregating the generators to the clustered buses. So in this network you still have up to 100 different wind generators, 2 at each bus on average.

In combination these two features allow you to study the spatial resolution of the transmission network separately from the spatial resolution of renewable generators. **Beware**: There is no clear evidence telling you what is a good representation of the full model. These options are under active study.

> Why we have a cluster function inside of the simplification method?

Why are you asking three times the same question?

> Is it possible to run the model without the simplification method / rule?
> I tryed to run the snakemake without the `s` for simplification. 

No, the network clustering methods in PyPSA's `networkclustering` module don't work reliably with multiple voltage levels and transformers. If it is somehow necessary for you we could include switches to make Step 2 and 3 optional as well. But that's about it.

**Comment by coroa** [comment]
Hmm .. thinking about it now, it would probably be clearer, if we moved the clustering step 4 from `simplify_network` into `cluster_network`.

**Comment by fneum** [comment]
Since you asked for it @JanFrederickUnnewehr, there's now a [documentation branch](https://github.com/PyPSA/PyPSA-Eur/tree/documentation) with a basic outline for a documentation (362f183) for which PRs can be prepared. These PRs can be incremental (e.g. about a specific rule). Once we have a good first issue we can pull this into the master branch.

Workflow: Fork this repository, checkout the branch `documentation`, make improvements, submit PR to branch `documentation`.

**Comment by fneum** [comment]
closed in #65
