### ISSUE TITLE
Fuel cell capital cost scaling

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#407]
I am wondering whether the following CAPEX scaling by efficiency still makes sense. As far as I understand the technology data repo already gives cost per MW_el. Can you confirm @lisazeyen? If so, we should remove this multiplication. 

https://github.com/PyPSA/pypsa-eur/blob/f5fd5299dd0a37b5a67c632ca905d779f593f28d/scripts/add_extra_components.py#L128

**Comment by lisazeyen** [comment]
Yes, the costs are given in MW_el. But since your bus0 for the fuel cell link is the H2 bus and the bus1 the electricity bus you should keep the scaling (the capital cost account for the input capacity at bus0 with are in your case then in units MW_H2). So you have to convert the costs in units MW_el -> cost in units MW_H2
