### ISSUE TITLE
Include deep geothermal potentials for district heating and electricity

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/pypsa-eur#541]
E.g. either Enhanced or Advanced Geothermal Systems. Cf. Aghahosseini and Breyer worldwide potentials in https://doi.org/10.1016/j.apenergy.2020.115769.

**Comment by LukasFrankenQ** [comment]
Update on this to make the process more transparent:

The first implementation of this was based on this [Breyer Paper](https://doi.org/10.1016/j.apenergy.2020.115769). In testing the following became clear. Due to the very optimistic estimations of future cost in that paper, the model would build geothermal in a greenfield scenario and later cost years on the scale of wind and solar in Germany, Austria, Switzerland and Italy. The reason costs become so low is that the paper assumes a 7.5% cost reduction per doubling of historically built capacity, while also assuming that EGS will be built exponentially more in the coming years. In my opinion, this makes it difficult to tune `EGS optimism` through a transparent and intelligible switch in the config to prevent excessive capacity expansion of a technology with highly unclear future cost.

It also does not consider deep hot aquifer which appears to be a highly relevant application relative to hot dry rock for electricity generation, nor more recent topics like flexible EGS that use the geothermal reservoir as a storage.

After conversations with Wilson Ricks, I am sold that it makes more sense to include a binary switch that represents either optimism in the future EGS cost (in particular the unlocking of advanced drilling) or pessimism. This is the implementation I am working on right now, and the one that I would use in the paper for which the cluster is steaming right now.

If we are interested in having the pessimistic version of EGS in the model, which would not be a great contributor to capacity, but might be useful for completeness sake, this is something I could implement very quickly, just let me know :)

I apologize for all of the delays, but it is really a particularly tricky technology, I am working on it.

**Comment by fneum** [comment]
closed via #733
