### ISSUE TITLE
Move data bundle to zenodo

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/pypsa-eur#60]
The PyPSA-Eur data bundle should also be versioned separately from PyPSA-Eur, since it's a large file (4 GB) and is updated less regularly.

**Comment by fneum** [comment]
What's the appropriate license for the data bundle and the cutouts?

**Comment by fneum** [comment]
There will be an analogous, but reduced data bundle and cutout archive for the tutorial. It does not include the GEBCO bathymetry data (minus 1.9 GB), no NATURA2000 shapefiles (minus 1.1 GB) (the compressed `tar.xz` only has 200 MB compared to 1.3 GB for the full dataset) and and limits the cutout to Germany and 1 month (50 MB instead of 3.9 GB)
