### ISSUE TITLE
Ensure complete set of carriers

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#633]
We should ensure that all carriers, that are used in the network, are actually listed in `n.carriers` with `nice_name` and `color`. 

For the set of existent carriers use `set.union(*[c.df.get("carrier", []) for c in n.iterate_components()])`

**Comment by euronion** [comment]
could be part of `.check_consistency()`?

**Comment by FabianHofmann** [comment]
yes, good idea

**Comment by virio-andreyana** [comment]
These are all carrier names from all components that is not included in n.carrier. As you can see, at least since the merger of pypsa-eur and pypsa-eur-sec, the term "carrier" has shifted away from meaning the energy carrier according to https://pypsa.readthedocs.io/en/latest/components.html#carrier into a way to categorize component with different properties.

| Buses                      | Generators    | Global Constraints | Lines | Links                                              | Stores          |
|----------------------------|---------------|--------------------|-------|----------------------------------------------------|-----------------|
| AC                         | solar rooftop | AC, DC             |       | BEV charger                                        | H2 Store        |
| DC                         | -             | co2_absorptions    | AC    | DAC                                                | battery storage |
| gas for industry           | -             | co2_emissions      | -     | DC                                                 | methanol        |
| low voltage                | -             | -                  | -     | Fischer-Tropsch                                    | -               |
| methanol                   | -             | -                  | -     | H2 Electrolysis                                    | -               |
| process emissions          | -             | -                  | -     | H2 Fuel Cell                                       | -               |
| solid biomass for industry | -             | -                  | -     | H2 electrolysis                                    | -               |
| -                          | -             | -                  | -     | H2 fuel cell                                       | -               |
| -                          | -             | -                  | -     | H2 pipeline                                        | -               |
| -                          | -             | -                  | -     | H2 pipeline retrofitted                            | -               |
| -                          | -             | -                  | -     | SMR                                                | -               |
| -                          | -             | -                  | -     | SMR CC                                             | -               |
| -                          | -             | -                  | -     | Sabatier                                           | -               |
| -                          | -             | -                  | -     | V2G                                                | -               |
| -                          | -             | -                  | -     | battery charger                                    | -               |
| -                          | -             | -                  | -     | battery discharger                                 | -               |
| -                          | -             | -                  | -     | biogas to gas                                      | -               |
| -                          | -             | -                  | -     | electricity distribution grid                      | -               |
| -                          | -             | -                  | -     | gas for industry                                   | -               |
| -                          | -             | -                  | -     | gas for industry CC                                | -               |
| -                          | -             | -                  | -     | gas pipeline                                       | -               |
| -                          | -             | -                  | -     | helmeth                                            | -               |
| -                          | -             | -                  | -     | home battery charger                               | -               |
| -                          | -             | -                  | -     | home battery discharger                            | -               |
| -                          | -             | -                  | -     | methanolisation                                    | -               |
| -                          | -             | -                  | -     | process emissions                                  | -               |
| -                          | -             | -                  | -     | process emissions CC                               | -               |
| -                          | -             | -                  | -     | residential rural biomass boiler                   | -               |
| -                          | -             | -                  | -     | residential rural gas boiler                       | -               |
| -                          | -             | -                  | -     | residential rural ground heat pump                 | -               |
| -                          | -             | -                  | -     | residential rural resistive heater                 | -               |
| -                          | -             | -                  | -     | residential rural water tanks charger              | -               |
| -                          | -             | -                  | -     | residential rural water tanks discharger           | -               |
| -                          | -             | -                  | -     | residential urban decentral air heat pump          | -               |
| -                          | -             | -                  | -     | residential urban decentral biomass boiler         | -               |
| -                          | -             | -                  | -     | residential urban decentral gas boiler             | -               |
| -                          | -             | -                  | -     | residential urban decentral resistive heater       | -               |
| -                          | -             | -                  | -     | residential urban decentral water tanks charger    | -               |
| -                          | -             | -                  | -     | residential urban decentral water tanks discharger | -               |
| -                          | -             | -                  | -     | services rural biomass boiler                      | -               |
| -                          | -             | -                  | -     | services rural gas boiler                          | -               |
| -                          | -             | -                  | -     | services rural ground heat pump                    | -               |
| -                          | -             | -                  | -     | services rural resistive heater                    | -               |
| -                          | -             | -                  | -     | services rural water tanks charger                 | -               |
| -                          | -             | -                  | -     | services rural water tanks discharger              | -               |
| -                          | -             | -                  | -     | services urban decentral air heat pump             | -               |
| -                          | -             | -                  | -     | services urban decentral biomass boiler            | -               |
| -                          | -             | -                  | -     | services urban decentral gas boiler                | -               |
| -                          | -             | -                  | -     | services urban decentral resistive heater          | -               |
| -                          | -             | -                  | -     | services urban decentral water tanks charger       | -               |
| -                          | -             | -                  | -     | services urban decentral water tanks discharger    | -               |
| -                          | -             | -                  | -     | solid biomass for industry                         | -               |
| -                          | -             | -                  | -     | solid biomass for industry CC                      | -               |
| -                          | -             | -                  | -     | urban central air heat pump                        | -               |
| -                          | -             | -                  | -     | urban central gas CHP                              | -               |
| -                          | -             | -                  | -     | urban central gas CHP CC                           | -               |
| -                          | -             | -                  | -     | urban central gas boiler                           | -               |
| -                          | -             | -                  | -     | urban central resistive heater                     | -               |
| -                          | -             | -                  | -     | urban central solid biomass CHP                    | -               |
| -                          | -             | -                  | -     | urban central solid biomass CHP CC                 | -               |
| -                          | -             | -                  | -     | urban central water tanks charger                  | -               |
| -                          | -             | -                  | -     | urban central water tanks discharger               | -               |
