### ISSUE TITLE
rolling_horizon produces wrong results

### ISSUE THREAD

**Issue by flo161616** [PyPSA/pypsa-eur#864]
I am using the 0.8.1 release of PyPSA-eur.

Description:
While attempting to solve a sector coupled network (CPLEX) with the option `rolling_horizon: true` it causes wrong results. No error occurs however. The Co2 Limits are not taken into account and as it seems, gas is used more often. Also it looks a bit as if the constraints are only taken account for the first iteration of the horizon.

How to reproduce:
Tested with CO2L0.76-24H-T-H-B-I-A. Single week, Belgium. Switching on the rolling horizon and choosing `horizon: 1` adds the horizon and completely changes the results.

Expected results:
Restrictions and results are the same as if no horizon was used.

**Comment by fneum** [comment]
In https://github.com/PyPSA/pypsa-eur/commit/c7d8af998cff59ce265dd285080e5e7330cf097c, I have revised the documentation to state that the `rolling_horizon: true` should only apply to the rule `solve_operations_networks` (e.g., no investment variables, no sector-coupling). I have also ensured now that the rolling horizon setting is only applied for this rule.

It is somewhat expected and intended that the emission limits are not considered in this case, as otherwise an assumption about the distribution of the budget to the operational optimisation windows would have to be made. In this case, it is better to remove the CO2 Limit and substitute it by an equivalent CO2 price.
